EducacionAvanzada/EducacionAvanzada.WebAdmin/Controllers/NotasController.cs
using EducacionAvanzada.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EducacionAvanzada.WebAdmin.Controllers
{
    [Authorize]
    public class NotasController : Controller
    {
        NotasBL _notasBL;
        AlumnosBL _alumnosBL;
        GradosBL _gradosBL;
        JornadasBL _jornadasBL;
        seccionBL _seccionesBL;

        public NotasController()
        {
            _notasBL = new NotasBL();
            _alumnosBL = new AlumnosBL();
            _gradosBL = new GradosBL();
            _jornadasBL = new JornadasBL();
            _seccionesBL = new seccionBL();
        }
        // GET: Notas
        public ActionResult Index()
        {
            var listadeNotas = _notasBL.ObtenerNotas();

            return View(listadeNotas);
        }


        public ActionResult Crear()
        {
            var nuevaNota = new Notas();
            var grados = _gradosBL.ObtenerGrados();
            var jornadas = _jornadasBL.ObtenerJornadas();
            var secciones = _seccionesBL.ObtenerSecciones();
            


            ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
            ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
            ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");


            return View(nuevaNota);
        }

        [HttpPost]
        public ActionResult Crear(Notas nota)
        {

            var grados = _gradosBL.ObtenerGrados();
            var jornadas = _jornadasBL.ObtenerJornadas();
            var secciones = _seccionesBL.ObtenerSecciones();


            if (ModelState.IsValid)
            {
                if (nota.GradoId == 0 || nota.JornadaId == 0 || nota.SeccionId == 0)
                {
                    if (nota.GradoId == 0)
                    {
                        ModelState.AddModelError("Grado", "Seleccione un grado");
                    }

                    if (nota.JornadaId == 0)
                    {
                        ModelState.AddModelError("Jornada", "Seleccione una Jornada");
                    }

                    if (nota.SeccionId == 0)
                    {
                        ModelState.AddModelError("seccion", "Seleccione una Sección");
                    }

                    ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
                    ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
                    ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");

                    return View(nota);
                }

                //Validacion del año
                var anioActual = Convert.ToInt32((DateTime.Now).Year);
                if (nota.Anio != anioActual)
                {
                    ModelState.AddModelError("Anio", "Ingrese el año correcto");

                    ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
                    ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
                    ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");

                    return View(nota);
                }

                _notasBL.GuardarNota(nota);

                return RedirectToAction("Index");
            }

           // var alumnos = _alumnosBL.ObtenerAlumnosactivo();

            ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
            ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
            ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");

            return View(nota);
        }

        public ActionResult Editar(int id)
        {
            var nota = _notasBL.ObtenerNota(id);
            var grados = _gradosBL.ObtenerGrados();
            var jornadas = _jornadasBL.ObtenerJornadas();
            var secciones = _seccionesBL.ObtenerSecciones();
            var alumnos = _alumnosBL.ObtenerAlumnosactivo();

            ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion", nota.GradoId);
            ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion", nota.JornadaId);
            ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion", nota.SeccionId);

            return View(nota);
        }

        [HttpPost]
        public ActionResult Editar(Notas nota)
        {
            var grados = _gradosBL.ObtenerGrados();
            var jornadas = _jornadasBL.ObtenerJornadas();
            var secciones = _seccionesBL.ObtenerSecciones();
           

            if (ModelState.IsValid)
            {
                

                if (nota.GradoId == 0 || nota.JornadaId == 0)
                {
                    if (nota.GradoId == 0)
                    {
                        ModelState.AddModelError("Grado", "Seleccione un grado");
                    }

                    if (nota.JornadaId == 0)
                    {
                        ModelState.AddModelError("Jornada", "Seleccione una Jornada");
                    }

                    ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
                    ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
                    ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");

                    return View(nota);
                }

                _notasBL.GuardarNota(nota);

                return RedirectToAction("Index");
            }

            ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
            ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
            ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");
            return View(nota);
        }

        public ActionResult Detalle(int id)
        {
            var nota = _notasBL.ObtenerNota(id);

            return View(nota);
        }

    }
}

EducacionAvanzada/EducacionAvanzada.WebAdmin/Controllers/NotasDetalleController.cs
using EducacionAvanzada.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EducacionAvanzada.WebAdmin.Controllers
{
    [Authorize]
    public class NotasDetalleController : Controller

    {
        NotasBL _notaBL;
        AlumnosBL _alumnosBL;
        materiaBL _MateriaBL;
        

        public NotasDetalleController()
        {
            _notaBL = new NotasBL();
            _alumnosBL = new AlumnosBL();
            _MateriaBL = new materiaBL();
        }
        // GET: NotasDetalle
        public ActionResult Index(int id)
        {
            var Notas = _notaBL.ObtenerNota(id);
            Notas.ListadeNotasDetalle = _notaBL.ObtenerNotasDetalle(id);
            return View(Notas);
        }

        public ActionResult Crear(int id)   
        {
            var nuevaNotasDetalle = new NotasDetalle();
            nuevaNotasDetalle.NotaId = id;

            var alumnos = _alumnosBL.ObtenerAlumnosactivo();
            ViewBag.AlumnoId = new SelectList(alumnos, "Id", "Nombre");

            var materias = _MateriaBL.Obtenermaterias();
            ViewBag.MateriaId = new SelectList(materias, "Id", "Descripcion");

            return View(nuevaNotasDetalle);
        }

        [HttpPost]
        public ActionResult Crear(NotasDetalle notasDetalle)
        {
            if(ModelState.IsValid)
            {
                if(notasDetalle.AlumnoId == 0)
                {
                    ModelState.AddModelError("AlumnoId", "Seleccione un Alumno");
                    return View(notasDetalle);
                }

                _notaBL.GuardarNotasDetalle(notasDetalle);
                return RedirectToAction("Index", new { id = notasDetalle.NotaId });
            }
            var alumnos = _alumnosBL.ObtenerAlumnosactivo();
            ViewBag.AlumnoId = new SelectList(alumnos, "Id", "Nombre");

            return View(notasDetalle);
        }

        public ActionResult Editar(int Id)
        {
            var notaDetalle = _notaBL.ObtenerNotasDetalleporId(Id);
            var alumnos = _alumnosBL.ObtenerAlumnos();
            var materias = _MateriaBL.Obtenermaterias();


            ViewBag.AlumnoId = new SelectList(alumnos, "Id", "Nombre", notaDetalle.AlumnoId);
            ViewBag.MateriaId = new SelectList(materias, "Id", "Descripcion", notaDetalle.MateriaId);
          


            return View(notaDetalle);
        }

        [HttpPost]
        public ActionResult Editar(NotasDetalle notaDetalle)
        {
            var alumnos = _alumnosBL.ObtenerAlumnosactivo();
            var materias = _MateriaBL.Obtenermaterias();

            if (ModelState.IsValid)
            {


                if (notaDetalle.AlumnoId == 0 || notaDetalle.MateriaId == 0)
                {
                    if (notaDetalle.AlumnoId == 0)
                    {
                        ModelState.AddModelError("Alumno", "Seleccione un Alumno");
                    }

                    if (notaDetalle.MateriaId == 0)
                    {
                        ModelState.AddModelError("Materia", "Seleccione una Materia");
                    }

                    ViewBag.AlumnoId = new SelectList(alumnos, "Id", "Nombre");
                    ViewBag.MateriaId = new SelectList(materias, "Id", "Descripcion");

                    return View(notaDetalle);
                }

                _notaBL.GuardarNotasDetalle(notaDetalle, true);

                return RedirectToAction("Index",new { id = notaDetalle.NotaId });
            }

            ViewBag.AlumnoId = new SelectList(alumnos, "Id", "Nombre");
            ViewBag.MateriaId = new SelectList(materias, "Id", "Descripcion");
            return View(notaDetalle);
        }



        public ActionResult Eliminar(int id)
        {
            var notaDetalle = _notaBL.ObtenerNotasDetalleporId(id);

            return View(notaDetalle);
        }
        [HttpPost]
        public ActionResult Eliminar(NotasDetalle notaDetalle)
        {
            _notaBL.EliminarNotaDetalle(notaDetalle.Id);
            return RedirectToAction("Index", new { id = notaDetalle.NotaId });
        }
    }
    
}

EducacionAvanzada/EducacionAvanzada.WebAdmin/Views/NotasDetalle/Crear.cshtml
@model EducacionAvanzada.BL.NotasDetalle

@{
    ViewBag.Title = "Crear";
}

<h2>Crear alumno para notas No: @Model.NotaId</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NotasDetalle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
  

        @Html.HiddenFor(model => model.NotaId)

        <div class="form-group">
            @Html.LabelFor(model => model.Alumno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AlumnoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AlumnoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Materia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MateriaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MateriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrimerParcial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrimerParcial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrimerParcial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SegundoParcial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SegundoParcial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SegundoParcial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TercerParcial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TercerParcial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TercerParcial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CuartoParcial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CuartoParcial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CuartoParcial, "", new { @class = "text-danger" })
            </div>
        </div>

  

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la Lista", "Index", "NotasDetalle", new { id = Model.NotaId }, null)
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

EducacionAvanzada/EducacionAvanzada.WebAdmin/Views/NotasDetalle/Editar.cshtml
@model EducacionAvanzada.BL.NotasDetalle

@{
    ViewBag.Title = "Editar";
}

<h2>Editar la NotaDetalle: @Model.Id</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NotasDetalle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        @Html.HiddenFor(model => model.NotaId)

        <div class="form-group">
            @Html.LabelFor(model => model.Alumno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AlumnoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AlumnoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Materia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MateriaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MateriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrimerParcial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrimerParcial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrimerParcial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SegundoParcial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SegundoParcial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SegundoParcial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TercerParcial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TercerParcial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TercerParcial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CuartoParcial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CuartoParcial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CuartoParcial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NotaFinal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NotaFinal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NotaFinal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la lista", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

EducacionAvanzada/EducacionAvanzada.WebAdmin/Views/NotasDetalle/Eliminar.cshtml
@model EducacionAvanzada.BL.NotasDetalle

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>¿Esta seguro que decea eliminar este registro?</h3>
<div>
    <h4>NotasDetalle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nota Numero:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NotaId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alumno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alumno.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Materia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Materia.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrimerParcial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrimerParcial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SegundoParcial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SegundoParcial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TercerParcial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TercerParcial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CuartoParcial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CuartoParcial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NotaFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NotaFinal)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.NotaId)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Regrear a la lista", "Index", new {id = Model.NotaId })
        </div>
    }
</div>

EducacionAvanzada/EducacionAvanzada.WebAdmin/Views/NotasDetalle/Index.cshtml
@model EducacionAvanzada.BL.Notas

@{
    ViewBag.Title = "Notas Detalle";
}

<h2>Detalle de Notas No: @Model.Id</h2>

<hr />

<div>
     
</div>

<p>
    @Html.ActionLink("Nueva Nota", "Crear" ,new { id = Model.Id })
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
           Alumno
        </th>
        <th>
            Materia
        </th>
        <th>
            PrimerParcial
        </th>
        <th>
            SegundoParcial
        </th>
        <th>
            TercerParcial
        </th>
        <th>
           CuartoParcial
        </th>
        <th>
            NotaFinal
        </th>

        <th></th>
    </tr>

@foreach (var item in Model.ListadeNotasDetalle) {
    <tr>
        <td>
            <img src="@item.Alumno.UrlImagen" alt="@item.Alumno.Nombre" style="max-width: 64px; height: auto;" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Alumno.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Materia.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PrimerParcial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SegundoParcial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TercerParcial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CuartoParcial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NotaFinal)
        <td>
        |
            @Html.ActionLink("Editar", "Editar", new { id = item.Id })
            @Html.ActionLink("Eliminar", "Eliminar", new { id=item.Id })
        </td>
    </tr>
}

</table>

@Html.ActionLink("Regresar a notas", "Index", "Notas")