EducacionAvanzada/EducacionAvanzada.WebAdmin/Controllers/AlumnosController.cs
using EducacionAvanzada.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EducacionAvanzada.WebAdmin.Controllers
{
    [Authorize]
    public class AlumnosController : Controller
    {
        AlumnosBL _alumnosBL;
        GradosBL _gradosBL;
        JornadasBL _jornadasBL;
        seccionBL _seccionesBL;
        PadresBL _padresBL;

        public AlumnosController()
        {
            _alumnosBL = new AlumnosBL();
            _gradosBL = new GradosBL();
            _jornadasBL = new JornadasBL();
            _seccionesBL = new seccionBL();
            _padresBL = new PadresBL();
        }

        // GET: Alumnos
        public ActionResult Index()
        {
            var listadeAlumnos = _alumnosBL.ObtenerAlumnos();

            return View(listadeAlumnos);
        }

        public ActionResult Crear()
        {
            var nuevoAlumno = new Alumno();
            var grados = _gradosBL.ObtenerGrados();
            var jornadas = _jornadasBL.ObtenerJornadas();
            var secciones = _seccionesBL.ObtenerSecciones();
            var padres = _padresBL.ObtenerPadres();

            ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
            ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
            ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");
            ViewBag.PadreId = new SelectList(padres, "Id", "Nombre");

            return View(nuevoAlumno);
        }

        [HttpPost]
        public ActionResult Crear(Alumno alumno, HttpPostedFileBase imagen)
        {
            string Url = alumno.UrlImagen;

            var grados = _gradosBL.ObtenerGrados();
            var jornadas = _jornadasBL.ObtenerJornadas();
            var secciones = _seccionesBL.ObtenerSecciones();



            if (ModelState.IsValid)
            {
                if (alumno.Nombre != alumno.Nombre.Trim())
                {
                    ModelState.AddModelError("Nombre", "No debe haber espacios al inicio o al final");
                    bolsaDeVista();
                    return View(alumno);
                }

                if (alumno.GradoId == 0 || alumno.JornadaId == 0 || alumno.SeccionId == 0)
                {
                    if (alumno.GradoId == 0)
                    {
                        ModelState.AddModelError("Grado", "Seleccione un grado");
                    }

                    if (alumno.JornadaId == 0)
                    {
                        ModelState.AddModelError("Jornada", "Seleccione una Jornada");
                    }

                    if (alumno.SeccionId == 0)
                    {
                        ModelState.AddModelError("seccion", "Seleccione una Sección");
                    }

                   // bolsaDeVista();
                    ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
                    ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
                    ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");


                    return View(alumno);
                }

                if (imagen != null)
                {
                    alumno.UrlImagen = GuardarImagen(imagen);
                }

                _alumnosBL.GuardarAlumno(alumno);

                return RedirectToAction("Index");
            }

            if (alumno.UrlImagen == null)
            {
                alumno.UrlImagen = Url;
            }

            ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
            ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
            ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");

            //bolsaDeVista();
            return View(alumno);
        }

        public void bolsaDeVista()
        {
            var grados = _gradosBL.ObtenerGrados();
            var jornadas = _jornadasBL.ObtenerJornadas();
            var secciones = _seccionesBL.ObtenerSecciones();

            ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
            ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
            ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");

        }

        public ActionResult Editar(int id)
        {
            var alumno = _alumnosBL.ObtenerAlumno(id);
            var grados = _gradosBL.ObtenerGrados();
            var jornadas = _jornadasBL.ObtenerJornadas();
            var secciones = _seccionesBL.ObtenerSecciones();


            ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion", alumno.GradoId);
            ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion", alumno.JornadaId);
            ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion", alumno.SeccionId);


            return View(alumno);
        }

        [HttpPost]
        public ActionResult Editar(Alumno alumno, HttpPostedFileBase imagen)
        {
            string Url = alumno.UrlImagen;

            if (ModelState.IsValid)
            {
                if (alumno.Nombre != alumno.Nombre.Trim())
                {
                    ModelState.AddModelError("Nombre", "No debe haber espacios al inicio o al final");
                    bolsaDeVista();
                    return View(alumno);
                }

                if (alumno.GradoId == 0 || alumno.JornadaId == 0)
                {
                    if (alumno.GradoId == 0)
                    {
                        ModelState.AddModelError("Grado", "Seleccione un grado");
                    }

                    if (alumno.JornadaId == 0)
                    {
                        ModelState.AddModelError("Jornada", "Seleccione una Jornada");
                    }

                    bolsaDeVista();

                    return View(alumno);
                }

                if (imagen != null)
                {
                    alumno.UrlImagen = GuardarImagen(imagen);
                }

                _alumnosBL.GuardarAlumno(alumno);

                return RedirectToAction("Index");
            }

            if (alumno.UrlImagen == null)
            {
                alumno.UrlImagen = Url;
            }
            bolsaDeVista();
            return View(alumno);
        }

        public ActionResult Detalle(int id)
        {
            var alumno = _alumnosBL.ObtenerAlumno(id);

            return View(alumno);
        }

        public ActionResult Eliminar(int id)
        {
            var alumno = _alumnosBL.ObtenerAlumno(id);

            return View(alumno);
        }

        [HttpPost]
        public ActionResult Eliminar(Alumno alumno)
        {
            _alumnosBL.EliminarAlumno(alumno.Id);
            return RedirectToAction("Index");
        }

        public string GuardarImagen(HttpPostedFileBase imagen)
        {
            string path = Server.MapPath("~/Imagenes/" + imagen.FileName);
            imagen.SaveAs(path);

            return "/Imagenes/" + imagen.FileName;
        }
    }
}

EducacionAvanzada/EducacionAvanzada.WebAdmin/Views/Alumnos/Crear.cshtml
@model EducacionAvanzada.BL.Alumno

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>

@using (Html.BeginForm("Crear", "Alumnos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Alumno</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Padre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PadreId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Padre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GradoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Grado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Jornada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("JornadaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Jornada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.seccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SeccionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.seccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Seleccionar Imagen</label>
            <div class="col-md-10">
                <input type="file" name="imagen" id="imagen"/>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class ="checkbox">
                    @Html.EditorFor(model => model.activo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.activo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EducacionAvanzada/EducacionAvanzada.WebAdmin/Views/Alumnos/Detalle.cshtml
@model EducacionAvanzada.BL.Alumno

@{
    ViewBag.Title = "Detalle";
}

<h2>Detalle</h2>

<div>
    <h4>Alumno</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grado.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Jornada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Jornada.Descripcion)
        </dd>

        <dt>
            Sección
        </dt>

        <dd>
            @Html.DisplayFor(model => model.seccion.Descripcion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UrlImagen)
        </dt>

        <dd>

            <img src="@Model.UrlImagen" alt="@Model.Nombre" style="width:200px; height: auto; " />
          </dd>
        <dt>
            @Html.DisplayNameFor(model => model.activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.activo)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.Id }) |
    @Html.ActionLink("Regresar a Lista de Alumnos", "Index")
</p>

EducacionAvanzada/EducacionAvanzada.WebAdmin/Views/Alumnos/Editar.cshtml
@model EducacionAvanzada.BL.Alumno

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm("Editar", "Alumnos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Alumno</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
    </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GradoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Grado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Jornada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("JornadaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Jornada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.seccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SeccionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SeccionId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Seleccionar Imagen</label>
            <div class="col-md-10">
                <input type="file" name="imagen" id="imagen" />
            </div>
            <div class="col-md-8">

                <img src="@Model.UrlImagen" alt="@Model.Nombre" style="width:200px; height: auto; " />
                <div class="form-group">
                    @Html.LabelFor(model => model.activo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">

                            @Html.EditorFor(model => model.activo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.activo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EducacionAvanzada/EducacionAvanzada.WebAdmin/Views/Alumnos/Eliminar.cshtml
@model EducacionAvanzada.BL.Alumno

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Alumno</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grado.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Jornada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Jornada.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.seccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.seccion.Descripcion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UrlImagen)
        </dt>

        <dd>

            <img src="@Model.UrlImagen" alt="@Model.Nombre" style="width:200px; height: auto; " />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.activo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.activo)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EducacionAvanzada/EducacionAvanzada.WebAdmin/Views/Alumnos/Index.cshtml
@model IEnumerable<EducacionAvanzada.BL.Alumno>

@{
    ViewBag.Title = "Alumnos";
}

<h2>Listado de Alumnos</h2>

<p>
    @Html.ActionLink("Nuevo Alumno", "Crear")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Jornada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.seccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UrlImagen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.activo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grado.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Jornada.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.seccion.Descripcion)
        </td>
        <td>
            <img src="@item.UrlImagen" alt="@item.Nombre" style="width:64px; height: auto; " />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.activo)
        </td>
        <td>

            @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
            @Html.ActionLink("Detalle", "Detalle", new { id = item.Id }) |
            @Html.ActionLink("Eliminar", "Eliminar", new { id = item.Id })
        </td>
    </tr>
}

</table>